name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    inputs: {}

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build site
        run: yarn build

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: out-gh-pages
          fetch-depth: 0

      - name: Prepare gh-pages branch
        run: |
          cd out-gh-pages

          git config user.name "Jonathan Samuel"
          git config user.email "Jonathan.Samuel@dell.com"

          if git show-ref --verify --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            git rm -rf .
          fi

      - name: Clear gh-pages contents
        run: |
          cd out-gh-pages
          git clean -fdx
          git rm -rf . 

      - name: Copy built site to gh-pages root
        run: cp -r out/* out-gh-pages/

      - name: Add a .nojekyll file
        run: touch out-gh-pages/.nojekyll

      - name: Commit and push changes
        run: |
          cd out-gh-pages
          git config user.name "Jonathan Samuel"
          git config user.email "Jonathan.Samuel@dell.com"
          git add -A

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Deploy site to gh-pages [skip ci]"
          fi

          git branch -M gh-pages
          git push -u origin gh-pages --force
